# Generated by Django 2.0.6 on 2018-06-24 23:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('weight', models.FloatField()),
            ],
            options={
                'db_table': 'security',
            },
        ),
        migrations.CreateModel(
            name='SecurityPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.FloatField()),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.Security')),
            ],
            options={
                'db_table': 'security_price',
            },
        ),
        migrations.CreateModel(
            name='SyntheticIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'synthetic_index',
            },
        ),
    ]
