# Generated by Django 2.0.6 on 2018-06-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='security',
            name='weight',
        ),
        migrations.AddField(
            model_name='securityprice',
            name='weight',
            field=models.FloatField(default=10.0),
        ),
    ]
